# Site settings
title: Viorel Stirbu - freelance full stack developer
description: "Hello. I'm Viorel, an experienced software developer from Romania specialized in Python/Javascript"
name: Viorel Stirbu
email: viorels@gmail.com
username: viorels
baseurl: ""
url: "http://www.stirbu.name"

# Build settings
markdown: kramdown
permalink: pretty
